# Tema VII

## Numpy

In [1]:
import numpy as np

### Arrays

In [2]:
arr = np.array(range(1,6))
arr

array([1, 2, 3, 4, 5])

In [3]:
arr[2]

np.int64(3)

### Matrices

In [4]:
matriz = np.array([[1,2,3],[4,5,6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

Comparando es espacio en memoria de una lista de Python y un array de Numpy. El array de Numpy is es, en este caso, 71% más pequeño que la lista.

In [5]:
import sys

lista_python = range(1000)
array_numpy = np.array(range(1000))

list_size = sys.getsizeof(1) * len(lista_python)
array_size = array_numpy.size * array_numpy.itemsize

print(list_size)
print(array_size)
print(array_numpy.itemsize)

28000
8000
8


Comparando el tiempo de ejecución de una resta en una lista de Python contra un array en Numpy.

In [6]:
import time

lista1 = range(1000000)
lista2 = range(1000000)

array1 = np.array(range(1000000))
array2 = np.array(range(1000000))

#tiempo de operación
inicio = time.time()
resultado = [x - y for x, y in zip(lista1, lista2)]
final = time.time()
print(f'La duración de la resta de lista es: {final - inicio}')

inicio = time.time()
resultado = array1 - array2
final = time.time()
print(f'La duración de la resta de array es: {final - inicio}')


La duración de la resta de lista es: 0.039897918701171875
La duración de la resta de array es: 0.0019989013671875


### Funciones Universales

#### Funciones Aritméticas

In [7]:
#substract()
array1 = np.array([4, 89, 15])
array2 = np.array([6, 39, 10])
np.subtract(array1, array2)

array([-2, 50,  5])

In [8]:
#add()
np.add(array1, array2)

array([ 10, 128,  25])

In [9]:
#multiply()
np.multiply(array1, array2)

array([  24, 3471,  150])

In [10]:
#divide()
np.divide(array1, array2)

array([0.66666667, 2.28205128, 1.5       ])

In [11]:
#power()
np.power(array1, array2)

array([               4096, 8803743584212754089,        576650390625])

In [12]:
#sqrt()
np.sqrt(array1)

array([2.        , 9.43398113, 3.87298335])

In [13]:
#square()
np.square(array1)

array([  16, 7921,  225])

In [14]:
#gcd() - máximo común divisor - greatest common denominator
np.gcd(array1, array2)

array([2, 1, 5])

In [15]:
#lcm() - mínimo común múltiplo - lowest common multiple
np.lcm(array1, array2)

array([  12, 3471,   30])

### Funciones de compración

In [16]:
#greater()
left = np.array([4, 89, 15])
right = np.array([6, 39, 10])
np.greater(left, right)

array([False,  True,  True])

In [18]:
#greater_equal()
np.greater_equal(left, right)

array([False,  True,  True])

In [19]:
#less()
np.less(left, right)

array([ True, False, False])

In [20]:
#less_equal()
np.less_equal(left, right)

array([ True, False, False])

In [21]:
#equal()
np.equal(left, right)

array([False, False, False])

In [22]:
#not_equal()
np.not_equal(left, right)

array([ True,  True,  True])

### Funciones Booleanas

In [23]:
#logical_and()
left = [True, False, True]
right = [False, False, True]
np.logical_and(left, right)

array([False, False,  True])

In [24]:
#logical_or()
np.logical_or(left, right)

array([ True, False,  True])

In [25]:
#logical_xor()
np.logical_xor(left, right)

array([ True, False, False])

In [27]:
#logical_not()
np.logical_not(left)

array([False,  True, False])

### Fuciones Estadisticas

In [3]:
#amin()
array = np.array(range(1,11))
print(f'Mínimo: {np.amin(array)}')

Mínimo: 1


In [8]:
matriz = np.array([[1,2,3,4], [5,6,7,8]])
print(f'Mínimo: {np.amin(matriz)}')

Mínimo: 1


In [34]:
#amax()
print(f'Máximo: {np.amax(array)}')
print(f'Máximo: {np.amax(matriz)}')

Máximo: 10
Máximo: 8


In [4]:
#percentile()
print(f'Percentile 25: {np.percentile(array, 25)}')

Percentile 25: 3.25


In [9]:
print(f'Percentile 25: {np.percentile(matriz, 25, axis=1)}')

Percentile 25: [1.75 5.75]


In [13]:
#median()
numbers = np.array(range(1,11))
print(f'Median: {np.median(numbers)}')

Median: 5.5


In [12]:
#mean()
print(f'Mean: {np.mean(numbers)}')

Mean: 6.0


In [28]:
#average()
suma = np.sum(numbers)
pesos = numbers / suma
print(f'Media Ponderada: {np.average(numbers, weights=pesos)}')
print(f'Media: {np.average(numbers)}')
print(f' Manual: {suma / len(numbers)}')

Media Ponderada: 7.0
Media: 5.5
Promedio Manual: 5.5


In [36]:
#std()
valores = np.array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60])
print(f'Desviación Estandar: {np.std(valores)}')

Desviación Estandar: 2.8722813232690143


In [37]:
#var()
print(f'Varianza: {np.var(valores)}')

Varianza: 8.25


## Pandas

In [16]:
import pandas as pd
import numpy as np

### Series en Pandas

In [4]:
serie = pd.Series([1,2,3,4,5], index= ['a', 'b', 'c', 'd', 'e'])
serie

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [5]:
#Otras formas de crear series
diccionario = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
serie1 = pd.Series(diccionario)
serie1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [8]:
serie['a']

np.int64(1)

In [11]:
print(serie.index)
print(serie.values)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[1 2 3 4 5]


In [22]:
#suma()
r = serie + serie1
print('Suma')
print(r)
print()

#multiplicación
print('Multiplicación')
print(serie * 10)
print()

#raiz cuadrada
print('Raiz Cuadrada')
sqr = np.sqrt(serie)
print(sqr)

Suma
a     2
b     4
c     6
d     8
e    10
dtype: int64

Multiplicación
a    10
b    20
c    30
d    40
e    50
dtype: int64

Raiz Cuadrada
a    1.000000
b    1.414214
c    1.732051
d    2.000000
e    2.236068
dtype: float64


### Dataframe en Pandas

#### Creando DataFrame

In [27]:
dic1 = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
dic2 = {'a': 6, 'b': 7, 'c': 8, 'd': 9, 'f': 10}

In [28]:
serie1 = pd.Series(dic1)
serie2 = pd.Series(dic2)
tabla = {'columna1': serie1, 'columna2': serie2}
df = pd.DataFrame(tabla)
df

columna1  columna2
a       1.0       6.0
b       2.0       7.0
c       3.0       8.0
d       4.0       9.0
e       5.0       NaN
f       NaN      10.0

In [30]:
#Creando dataframe mediante una lista de diccionarios
dic3 = {'a': 11, 'b': 12, 'c': 13, 'd': 14, 'f': 15}
df = pd.DataFrame([dic1, dic2, dic3])
df

a   b   c   d    e     f
0   1   2   3   4  5.0   NaN
1   6   7   8   9  NaN  10.0
2  11  12  13  14  NaN  15.0

#### Operaciones con DataFrame

In [31]:
#Consultando el dataframe
df['a']

0     1
1     6
2    11
Name: a, dtype: int64

In [103]:
#Agregar nueva columna al DataFrame
serie1 = pd.Series(dic1)
serie2 = pd.Series(dic2)
tabla = {'columna1': serie1, 'columna2': serie2}
df = pd.DataFrame(tabla)
df
columna3 = pd.Series({'a': 11, 'b': 12, 'c': 13, 'd': 14, 'f': 15})
df['Columna3'] = columna3
df


columna1  columna2  Columna3
a       1.0       6.0      11.0
b       2.0       7.0      12.0
c       3.0       8.0      13.0
d       4.0       9.0      14.0
e       5.0       NaN       NaN
f       NaN      10.0      15.0

In [35]:
#Delete a column from the DataFrame
del df['Columna3']
df

columna1  columna2
a       1.0       6.0
b       2.0       7.0
c       3.0       8.0
d       4.0       9.0
e       5.0       NaN
f       NaN      10.0

In [36]:
#Accediendo a las filas por sus etiquetas
df.loc['a']

columna1    1.0
columna2    6.0
Name: a, dtype: float64

In [40]:
#Accediendo a las filas por su posición
df.iloc[2:5]

columna1  columna2
c       3.0       8.0
d       4.0       9.0
e       5.0       NaN

In [45]:
#Accediendo a las filas por array booleano
filtro = np.less_equal(df['columna1'], df['columna2'])
print(filtro)
df[filtro]

a     True
b     True
c     True
d     True
e    False
f    False
dtype: bool


columna1  columna2
a       1.0       6.0
b       2.0       7.0
c       3.0       8.0
d       4.0       9.0

In [51]:
#multiplicación
res = df * 2
res

columna1  columna2
a       2.0      12.0
b       4.0      14.0
c       6.0      16.0
d       8.0      18.0
e      10.0       NaN
f       NaN      20.0

In [49]:
#Suma
df + res

columna1  columna2
a       3.0      18.0
b       6.0      21.0
c       9.0      24.0
d      12.0      27.0
e      15.0       NaN
f       NaN      30.0

In [52]:
#Raiz Cuadrada
np.sqrt(df)

columna1  columna2
a  1.000000  2.449490
b  1.414214  2.645751
c  1.732051  2.828427
d  2.000000  3.000000
e  2.236068       NaN
f       NaN  3.162278

In [54]:
#La Transpuesta
serie1 = pd.Series(dic1)
serie2 = pd.Series(dic2)
tabla = {'columna1': serie1, 'columna2': serie2}
df1 = pd.DataFrame(tabla)
print(df1)

df2 = pd.DataFrame([dic1, dic2])
print(df2)
df1.T


   columna1  columna2
a       1.0       6.0
b       2.0       7.0
c       3.0       8.0
d       4.0       9.0
e       5.0       NaN
f       NaN      10.0
   a  b  c  d    e     f
0  1  2  3  4  5.0   NaN
1  6  7  8  9  NaN  10.0


a    b    c    d    e     f
columna1  1.0  2.0  3.0  4.0  5.0   NaN
columna2  6.0  7.0  8.0  9.0  NaN  10.0

#### Funciones de Gestión de Datos

In [114]:
diccionario = {'user3': pd. Series ( ['Juan' , 'Barcelona', 32, 'Soltero', 'Hombre', 45 ], index=['nombre', 'localidad' , 'edad' ,'estado civil', 'sexo', 'salario' ]),
'user4': pd. Series ( ['Alicia', 'Santander' , 47, 'Casado' , 'Mujer',78 ], index=['nombre' , 'localidad' , 'edad' , 'estado civil','sexo', 'salario' ] ),
'user2': pd. Series ( ['Marcos' , 'Madrid' , 31, 'Casado' , 'Hombre',120 ], index=['nombre' , 'localidad' , 'edad' , 'estado civil','sexo', 'salario' ] ),
'user1': pd. Series ( ['Isabel', 'Zaragoza' , 70, 'Soltero' , 'Mujer',92 ], index=['nombre' , 'localidad', 'edad' , 'estado civil','sexo', 'salario' ] ) }
df = pd.DataFrame(diccionario).T
df

nombre  localidad edad estado civil    sexo salario
user3    Juan  Barcelona   32      Soltero  Hombre      45
user4  Alicia  Santander   47       Casado   Mujer      78
user2  Marcos     Madrid   31       Casado  Hombre     120
user1  Isabel   Zaragoza   70      Soltero   Mujer      92

In [62]:
df.sort_values('edad', ascending=False)

nombre  localidad edad estado civil    sexo
userl  Isabel   Zaragoza   70      Soltero   Mujer
user4  Alicia  Santander   47       Casado   Mujer
user3    Juan  Barcelona   32      Soltero  Hombre
user2  Marcos     Madrid   31       Casado  Hombre

In [65]:
df.sort_index()

nombre  localidad edad estado civil    sexo
user1  Isabel   Zaragoza   70      Soltero   Mujer
user2  Marcos     Madrid   31       Casado  Hombre
user3    Juan  Barcelona   32      Soltero  Hombre
user4  Alicia  Santander   47       Casado   Mujer

In [74]:
#Agrupar por estado civil y contar cuando elementos en cada grupo
df.groupby('sexo').count()


nombre  localidad  edad  estado civil
sexo                                         
Hombre       2          2     2             2
Mujer        2          2     2             2

In [120]:
#Función apply
def format_salary(x):
    return x * 1000
    
df['salario formateado'] = df['salario'].apply(format_salary)
df

nombre  localidad edad estado civil    sexo salario  salario formateado
user3    Juan  Barcelona   32      Soltero  Hombre      45               45000
user4  Alicia  Santander   47       Casado   Mujer      78               78000
user2  Marcos     Madrid   31       Casado  Hombre     120              120000
user1  Isabel   Zaragoza   70      Soltero   Mujer      92               92000

In [125]:
df.describe()

salario formateado
count            4.000000
mean         83750.000000
std          31180.923655
min          45000.000000
25%          69750.000000
50%          85000.000000
75%          99000.000000
max         120000.000000

#### Lectura y escritura de ficheros

In [130]:
movies = pd.read_csv('movies.csv')
movies.sort_values('Rating', ascending=False)

Title      Genre  \
7                        The Shawshank Redemption      Drama   
5                                   The Godfather      Crime   
1                                 The Dark Knight     Action   
15                               Schindler's List      Drama   
13  The Lord of the Rings: The Return of the King    Fantasy   
4                                    Pulp Fiction      Crime   
0                                       Inception     Sci-Fi   
6                                    Forrest Gump      Drama   
19                                     Goodfellas      Crime   
3                                      The Matrix     Sci-Fi   
2                                    Interstellar     Sci-Fi   
14                          Star Wars: A New Hope     Sci-Fi   
18                       The Silence of the Lambs   Thriller   
16                                      Gladiator     Action   
11                                  The Lion King  Animation   
17                                     Braveheart      Drama   
12                                  Jurassic Park     Sci-Fi   
8                                    The Avengers     Action   
10                                         Avatar     Sci-Fi   
9                                         Titanic    Romance   

                Director  Release Year  Duration (minutes)  Rating  \
7         Frank Darabont          1994                 142     9.3   
5   Francis Ford Coppola          1972                 175     9.2   
1      Christopher Nolan          2008                 152     9.0   
15      Steven Spielberg          1993                 195     9.0   
13         Peter Jackson          2003                 201     8.9   
4      Quentin Tarantino          1994                 154     8.9   
0      Christopher Nolan          2010                 148     8.8   
6        Robert Zemeckis          1994                 142     8.8   
19       Martin Scorsese          1990                 146     8.7   
3         The Wachowskis          1999                 136     8.7   
2      Christopher Nolan          2014                 169     8.6   
14          George Lucas          1977                 121     8.6   
18        Jonathan Demme          1991                 118     8.6   
16          Ridley Scott          2000                 155     8.5   
11          Roger Allers          1994                  88     8.5   
17            Mel Gibson          1995                 178     8.3   
12      Steven Spielberg          1993                 127     8.1   
8            Joss Whedon          2012                 143     8.0   
10         James Cameron          2009                 162     7.8   
9          James Cameron          1997                 195     7.8   

    Box Office (Million $)  
7                     58.3  
5                    246.1  
1                   1004.6  
15                   322.2  
13                  1142.0  
4                    214.2  
0                    829.9  
6                    678.2  
19                    46.8  
3                    463.5  
2                    677.5  
14                   775.4  
18                   272.7  
16                   457.6  
11                   968.5  
17                   213.2  
12                  1033.9  
8                   1518.8  
10                  2788.0  
9                   2200.0

In [131]:
movies.describe()

Release Year  Duration (minutes)    Rating  Box Office (Million $)
count     20.000000           20.000000  20.00000               20.000000
mean    1996.950000          152.350000   8.60500              795.570000
std       10.708949           28.219581   0.42609              708.973705
min     1972.000000           88.000000   7.80000               46.800000
25%     1993.000000          140.500000   8.45000              266.050000
50%     1994.500000          150.000000   8.65000              677.850000
75%     2004.250000          170.500000   8.90000             1011.925000
max     2014.000000          201.000000   9.30000             2788.000000

In [134]:
movies[movies['Release Year'] <= 1995]

Title      Genre              Director  Release Year  \
4               Pulp Fiction      Crime     Quentin Tarantino          1994   
5              The Godfather      Crime  Francis Ford Coppola          1972   
6               Forrest Gump      Drama       Robert Zemeckis          1994   
7   The Shawshank Redemption      Drama        Frank Darabont          1994   
11             The Lion King  Animation          Roger Allers          1994   
12             Jurassic Park     Sci-Fi      Steven Spielberg          1993   
14     Star Wars: A New Hope     Sci-Fi          George Lucas          1977   
15          Schindler's List      Drama      Steven Spielberg          1993   
17                Braveheart      Drama            Mel Gibson          1995   
18  The Silence of the Lambs   Thriller        Jonathan Demme          1991   
19                Goodfellas      Crime       Martin Scorsese          1990   

    Duration (minutes)  Rating  Box Office (Million $)  
4                  154     8.9                   214.2  
5                  175     9.2                   246.1  
6                  142     8.8                   678.2  
7                  142     9.3                    58.3  
11                  88     8.5                   968.5  
12                 127     8.1                  1033.9  
14                 121     8.6                   775.4  
15                 195     9.0                   322.2  
17                 178     8.3                   213.2  
18                 118     8.6                   272.7  
19                 146     8.7                    46.8