# Tema VII

## Numpy

In [1]:
import numpy as np

### Arrays

In [2]:
arr = np.array(range(1,6))
arr

array([1, 2, 3, 4, 5])

In [3]:
arr[2]

np.int64(3)

### Matrices

In [4]:
matriz = np.array([[1,2,3],[4,5,6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

Comparando es espacio en memoria de una lista de Python y un array de Numpy. El array de Numpy is es, en este caso, 71% más pequeño que la lista.

In [5]:
import sys

lista_python = range(1000)
array_numpy = np.array(range(1000))

list_size = sys.getsizeof(1) * len(lista_python)
array_size = array_numpy.size * array_numpy.itemsize

print(list_size)
print(array_size)
print(array_numpy.itemsize)

28000
8000
8


Comparando el tiempo de ejecución de una resta en una lista de Python contra un array en Numpy.

In [7]:
import time

lista1 = range(1000000)
lista2 = range(1000000)

array1 = np.array(range(1000000))
array2 = np.array(range(1000000))

#tiempo de operación
inicio = time.time()
resultado = [x - y for x, y in zip(lista1, lista2)]
final = time.time()
print(f'La duración de la resta de lista es: {final - inicio}')

inicio = time.time()
resultado = array1 - array2
final = time.time()
print(f'La duración de la resta de array es: {final - inicio}')


La duración de la resta de lista es: 0.039556026458740234
La duración de la resta de array es: 0.0019991397857666016


### Funciones Universales

#### Funciones Aritméticas

In [8]:
#substract()
array1 = np.array([4, 89, 15])
array2 = np.array([6, 39, 10])
np.subtract(array1, array2)

array([-2, 50,  5])

In [9]:
#add()
np.add(array1, array2)

array([ 10, 128,  25])

In [10]:
#multiply()
np.multiply(array1, array2)

array([  24, 3471,  150])

In [11]:
#divide()
np.divide(array1, array2)

array([0.66666667, 2.28205128, 1.5       ])

In [12]:
#power()
np.power(array1, array2)

array([               4096, 8803743584212754089,        576650390625])

In [15]:
#sqrt()
np.sqrt(array1)

array([2.        , 9.43398113, 3.87298335])

In [16]:
#square()
np.square(array1)

array([  16, 7921,  225])

In [17]:
#gcd() - máximo común divisor - greatest common denominator
np.gcd(array1, array2)

array([2, 1, 5])

In [18]:
#lcm() - mínimo común múltiplo - lowest common multiple
np.lcm(array1, array2)

array([  12, 3471,   30])

### Funciones de compración